#!/usr/bin/env bash
# configuring nginx to run on port 80

sudo apt-get remove nginx -y
sudo apt-get purge nginx -y
sudo apt-get install nginx -y

# Modify the Nginx configuration file to listen on all active IPv4 IPs
sudo sed -i 's/listen 80;/listen 0.0.0.0:80;/' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo systemctl restart nginx

