#!/usr/bin/env bash
# Reads the /etc/passwd file and return \
# username
# user id
# Home directory path for the user

while read -r passwd;
do
    echo "$passwd" | cut -d ":" -f1,3,6
done < "/etc/passwd"