#!/usr/bin/env bash
# using case and while loop

counter=0

while [[ $counter -le 20 ]]
do
    echo $counter
    case $counter in
        4)
            echo "bad luck from China";;
        9)
            echo "bad luck from Japan";;
        17)
            echo "bad luck from Italy";;
    esac
    (( counter++ ))
done